# Generated by Django 5.2.13 on 2026-05-01 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название вуза')),
                ('short_name', models.CharField(max_length=50, verbose_name='Аббревиатура')),
                ('website', models.URLField(blank=True, verbose_name='Сайт вуза')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('it_directions', models.TextField(blank=True, verbose_name='IT направления')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='universities/', verbose_name='Логотип')),
            ],
            options={
                'verbose_name': 'Вуз',
                'verbose_name_plural': 'Вузы',
                'ordering': ['short_name'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название компании')),
                ('company_type', models.CharField(choices=[('commercial', 'Коммерческая компания'), ('university', 'Компания при вузе / НИИ'), ('startup', 'Стартап'), ('government', 'Государственная структура')], default='commercial', max_length=20, verbose_name='Тип компании')),
                ('description', models.TextField(blank=True, verbose_name='Описание компании')),
                ('website', models.URLField(blank=True, verbose_name='Сайт компании')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='companies/', verbose_name='Логотип')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email для связи')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Проверена')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to=settings.AUTH_USER_MODEL, verbose_name='Владелец аккаунта')),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='internships.university', verbose_name='Аффилированный вуз')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название стажировки')),
                ('field', models.CharField(choices=[('backend', 'Backend-разработка'), ('frontend', 'Frontend-разработка'), ('fullstack', 'Fullstack-разработка'), ('mobile', 'Мобильная разработка'), ('devops', 'DevOps / Инфраструктура'), ('data', 'Data Science / ML / AI'), ('qa', 'Тестирование (QA)'), ('design', 'UI/UX Дизайн'), ('security', 'Информационная безопасность'), ('pm', 'Управление проектами (PM)'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Направление')),
                ('description', models.TextField(verbose_name='Описание стажировки')),
                ('requirements', models.TextField(blank=True, verbose_name='Требования')),
                ('tasks', models.TextField(blank=True, verbose_name='Задачи стажёра')),
                ('format', models.CharField(choices=[('office', 'Офис'), ('remote', 'Удалённо'), ('hybrid', 'Гибрид')], default='office', max_length=10, verbose_name='Формат работы')),
                ('duration', models.CharField(blank=True, help_text='Например: 2 месяца, лето 2025', max_length=100, verbose_name='Продолжительность')),
                ('stipend', models.CharField(blank=True, help_text="Например: 15 000 руб/мес или 'Не оплачивается'", max_length=100, verbose_name='Стипендия / Оплата')),
                ('spots', models.PositiveIntegerField(default=1, verbose_name='Количество мест')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Дедлайн подачи заявок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internships', to='internships.company', verbose_name='Компания')),
                ('university_partnership', models.ManyToManyField(blank=True, help_text='Вузы, студентам которых отдаётся предпочтение', to='internships.university', verbose_name='Партнёрство с вузами')),
            ],
            options={
                'verbose_name': 'Стажировка',
                'verbose_name_plural': 'Стажировки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hh_resume_url', models.URLField(blank=True, help_text='Вставьте ссылку на ваше резюме с hh.ru (например: https://hh.ru/resume/...)', verbose_name='Ссылка на резюме hh.ru')),
                ('resume_file', models.FileField(blank=True, help_text='Загрузите резюме в формате PDF или DOCX', null=True, upload_to='resumes/', verbose_name='Резюме (файл)')),
                ('cover_letter', models.TextField(blank=True, help_text='Расскажите, почему вы подходите для этой стажировки', verbose_name='Сопроводительное письмо')),
                ('course', models.CharField(blank=True, help_text='Например: 3 курс, магистратура 1 год', max_length=20, verbose_name='Курс')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('reviewing', 'Изучается'), ('interview', 'Приглашён на интервью'), ('accepted', 'Принят'), ('rejected', 'Отказ')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='Соискатель')),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='internships.internship', verbose_name='Стажировка')),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='internships.university', verbose_name='Вуз соискателя')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
                'unique_together': {('internship', 'applicant')},
            },
        ),
    ]
