# Generated by Django 5.2.14 on 2026-05-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0002_internship_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='company_message',
            field=models.TextField(blank=True, help_text='Сообщение, которое отправляется соискателю', verbose_name='Сообщение от компании'),
        ),
        migrations.AddField(
            model_name='application',
            name='company_message_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата сообщения от компании'),
        ),
        migrations.AddField(
            model_name='application',
            name='company_message_read',
            field=models.BooleanField(default=False, verbose_name='Прочитано соискателем'),
        ),
    ]
